apiVersion: v1
kind: Secret
metadata:
  name: aion-k8s
type: Opaque
stringData:
  APP_KEY: "base64:g9+a+bFaid5agFYGkjONs8F5cFtjYG04gUZAzMfMCQ4="

  DB_USERNAME: "admin"
  DB_PASSWORD: "hunnuw-hijrex-Mywky8"
  
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""

  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  MAIL_USERNAME: "aion@nutriton.com.mx"
  MAIL_PASSWORD: ")9$+@wEGeTQx"

  #SENTRY_LARAVEL_DSN: "https://xxxxxxxxxxxxxx@xxxxxxxx.ingest.sentry.io/xxxxxxxxxx"
