apiVersion: v1
kind: ConfigMap
metadata:
  name: aion-k8s
data:
  APP_NAME: "Aion"
  APP_ENV: "local"
  APP_KEY: "base64:3yATZvXyZqfNTBPSAqnesT+diebh7t4jR4m95heWawo="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "http://localhost:8000"

  APP_LOCALE: "es"
  APP_FALLBACK_LOCALE: "es"
  APP_FAKER_LOCALE: "es_MX"

  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "aion-dev.cp2fru4abzgq.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_DATABASE: "aion-dev"
  
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  CACHE_PREFIX: ""

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "mail.nutriton.com.mx"
  MAIL_PORT: "465"

  MAIL_ENCRYPTION: "TLS/SSL"
  MAIL_FROM_ADDRESS: "aion@nutriton.com.mx"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  VITE_APP_NAME: "${APP_NAME}"
